### ISSUE TITLE
A better help command

### ISSUE THREAD

**Issue by Mad880** [ThePoleThatFishes/Turbine-Bot#1]
Try making a better help command, by that i mean you don't need to make a help command and manually put all the command names in it, you could just make a cog and a class that for a help command and make it much better and easier, try looking at examples and etc. good luck

**Comment by ThePoleThatFishes** [comment]
I decided against using the inbuilt help command, since the bot pretty much only has one purpose, therefore one cog. Also, I wanted to use my own help command, didn't particularly like how it was displayed.
